### ISSUE TITLE
Batch file closes at choco install

### ISSUE THREAD

**Issue by saschabrockel** [koppor/koppors-chocolatey-scripts#4]
Hey there. I've tried to create a batch file for choco installations for myself and now I've found your repo and with your code, I have the exact same issue. 

As soon as I get to any `choco install` line the cmd window just closes and has installed nothing. I'm using Windows 10 with its latest version. Do I need anything else to get it running that I'm missing? I've tried your install.bat.

**Comment by koppor** [comment]
Do you have `cmd` started in adminstrator mode?

Which windows?

    > ver

    Microsoft Windows [Version 10.0.19042.964]

Works here

![grafik](https://user-images.githubusercontent.com/1366654/116938582-42f89e80-ac6b-11eb-8bef-174b53500288.png)

**Comment by koppor** [comment]
Without any minimal example, I cannot help.

After re-reading, I thought, that `pause` (https://github.com/koppor/koppors-chocolatey-scripts/blob/2af2fcf1f29d366634fe5810823a5ec99e6a9b31/install.bat#L229) might be missing, but this does not seem to be the question.

Please execute `choco install jabref` in a console with administrator rights and provide the output.

I will close the issue until I receive feedback to keep the numbers of opened issues low :)
